#!/usr/bin/python
# -*- coding: UTF-8
        
"""The basic command that starts up the commandline interface"""

from eellib import Commandline
#from Commandline import Commandline
import sys


# $Log$
# Revision 1.1  2004/12/14 13:07:52  kpalin
#
# Name change from MABS to EEL (Enhancer Element Locator / Monty Python pun
# "My hovercraft is full of EELs" )
#
# Revision 1.5  2004/10/21 12:46:31  kpalin
# Removed reference to a specific version of python (2.2)
#
# Revision 1.4  2004/01/14 10:04:19  kpalin
# Added documentation
#
# Revision 1.3  2004/01/13 07:54:35  kpalin
# Paljon kaiken laista.
#
# setup.py: debug asetukset saa komentoriviltä
#
# Revision 1.2  2003/12/12 12:34:57  kpalin
# Lisättiin loki ja tulostettava ID
#


cl=Commandline.Commandline()

if len(sys.argv)==1:
    print "$Id$"
    try:
        cl.run()
    except EOFError:
        pass
else:
    commands=''
    for i in range(1, len(sys.argv)):
        commands += ' '+sys.argv[i]
    commands=commands.split(' -')[1:]

    error=0
    for c in commands:
        if not cl.isCommand(c.split()[0]):
            print 'unknown argument: -'+c.split()[0]
            error=1

    if error or commands==[]:
        cl.help(['add -'])
    else:
        for c in commands:
            cl.execute(c)
