#!/usr/bin/python2.2 

from mabslib import Commandline
#from Commandline import Commandline
import sys


# $Log$
# Revision 1.2  2003/12/12 12:34:57  kpalin
# Lisättiin loki ja tulostettava ID
#


cl=Commandline.Commandline()

if len(sys.argv)==1:
    print "$Id$"
    try:
        cl.run()
    except EOFError:
        pass
else:
    commands=''
    for i in range(1, len(sys.argv)):
        commands += ' '+sys.argv[i]
    commands=commands.split(' -')[1:]

    error=0
    for c in commands:
        if not cl.isCommand(c.split()[0]):
            print 'unknown argument: -'+c.split()[0]
            error=1

    if error or commands==[]:
        cl.help(['add -'])
    else:
        for c in commands:
            cl.execute(c)
