#!/usr/bin/python2.2 

from mabslib.Commandline import Commandline
import sys

cl=Commandline()

if len(sys.argv)==1:
    try:
        cl.run()
    except EOFError:
        pass
else:
    commands=''
    for i in range(1, len(sys.argv)):
        commands += ' '+sys.argv[i]
    commands=commands.split(' -')[1:]

    error=False
    for c in commands:
        if not cl.isCommand(c.split()[0]):
            print 'unknown argument: -'+c.split()[0]
            error=True

    if error or commands==[]:
        cl.help(['add -'])
    else:
        for c in commands:
            cl.execute(c)
